USE [master]
GO

/****** Object:  Database [ATF_Bank]    Script Date: 28.01.2023 15:26:59 ******/
CREATE DATABASE [ATF_Bank]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ATF_Bank', FILENAME = N'E:\DataBase\MSSQL16.SQLEXPRESS\MSSQL\DATA\ATF_Bank.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ATF_Bank_log', FILENAME = N'E:\DataBase\MSSQL16.SQLEXPRESS\MSSQL\DATA\ATF_Bank_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ATF_Bank].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ATF_Bank] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ATF_Bank] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ATF_Bank] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ATF_Bank] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ATF_Bank] SET ARITHABORT OFF 
GO

ALTER DATABASE [ATF_Bank] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ATF_Bank] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ATF_Bank] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ATF_Bank] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ATF_Bank] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ATF_Bank] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ATF_Bank] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ATF_Bank] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ATF_Bank] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ATF_Bank] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ATF_Bank] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ATF_Bank] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ATF_Bank] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ATF_Bank] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ATF_Bank] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ATF_Bank] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ATF_Bank] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ATF_Bank] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ATF_Bank] SET  MULTI_USER 
GO

ALTER DATABASE [ATF_Bank] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ATF_Bank] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ATF_Bank] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ATF_Bank] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ATF_Bank] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ATF_Bank] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ATF_Bank] SET QUERY_STORE = ON
GO

ALTER DATABASE [ATF_Bank] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ATF_Bank] SET  READ_WRITE 
GO

